// <auto-generated />
using System;
using ExamCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamCalculator.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20210821193155_AddedExams")]
    partial class AddedExams
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ExamCalculator.Data.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamCalculator.Data.ExamTask", b =>
                {
                    b.Property<Guid>("ExamTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<float>("MaximumPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("ExamTaskId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamTasks");
                });

            modelBuilder.Entity("ExamCalculator.Data.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ExamCalculator.Data.Pupil", b =>
                {
                    b.Property<Guid>("PupilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("PupilId");

                    b.ToTable("Pupils");
                });

            modelBuilder.Entity("GroupPupil", b =>
                {
                    b.Property<Guid>("GroupsGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PupilsPupilId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupsGroupId", "PupilsPupilId");

                    b.HasIndex("PupilsPupilId");

                    b.ToTable("GroupPupil");
                });

            modelBuilder.Entity("ExamCalculator.Data.ExamTask", b =>
                {
                    b.HasOne("ExamCalculator.Data.Exam", "Exam")
                        .WithMany("Tasks")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("GroupPupil", b =>
                {
                    b.HasOne("ExamCalculator.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamCalculator.Data.Pupil", null)
                        .WithMany()
                        .HasForeignKey("PupilsPupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamCalculator.Data.Exam", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
