name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
  release:
#    types:
#     - created


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: 
          # - Debug
          - Release
        runtime: 
          - win7-x64
          - linux-x64
          - osx-x64

    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ExamCalculator.sln                       

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    
    - name: Build
      working-directory: 'ExamCalculator.UI'
      run:  dotnet publish -p:PublishSingleFile=true -p:PublishTrimmed=True -p:TrimMode=Link --output "${{ env.GITHUB_WORKSPACE }}/publish" -c  ${{ matrix.configuration }} -r ${{ matrix.runtime }}
    
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "Klausurverwaltung-${{ matrix.runtime }}-${{ matrix.configuration }}"
        path: "${{ env.GITHUB_WORKSPACE }}/publish"
    
    - name: Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        draft: True
        allowUpdates: True
        artifacts: "Klausurverwaltung-${{ matrix.runtime }}-${{ matrix.configuration }}"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
